config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  get 'home/about', to:  'homes#about'
   resources :books, only: [:new, :create, :index, :show, :destroy, :edit, :update]
   resources :users, only: [:show, :index, :edit, :update, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  attachment :image


  validates :title,  presence: true, length: { in: 2..200 }
  validates :body, presence: true, length: { in: 2..200 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

          has_many :books, dependent: :destroy
          attachment :profile_image


           validates :name, presence: true, length: { in: 2..20 }, uniqueness: true
           validates :introduction, length: { maximum: 50}


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
     before_action :authenticate_user!,except: [:top, :about]

    before_action :configure_permitted_parameters, if: :devise_controller?

     def after_sign_in_path_for(resource)
      user_path(@user.id)
     end




  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

   def index
    flash[:notice] = "ログイン済ユーザーのみ記事の詳細を確認できます" unless user_signed_in?
   end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def new
    @book = Book
  end

  def create
       @book = Book.new(book_params)
       @book.user_id = current_user.id
       @user = current_user
       @books = Book.all
    if @book.save
       flash[:notice] = 'You have created book successfully.'
       redirect_to book_path(@book.id)
    else
       render :index
    end

  end


  def index
    @books = Book.all
    @book = Book.new
    @user = current_user
  end

  def show
    @book = Book.find(params[:id])
    @new_book = Book.new
    @user = @book.user
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  def edit
     @book = Book.find(params[:id])
  if @book.user != current_user
    redirect_to books_path
  end

  end

  def update
       @new_book = Book.new
       @book = Book.find(params[:id])
       @book.user_id = current_user.id
   if  @book.update(book_params)
       flash[:notice] = 'You have updated book successfully.'
      redirect_to book_path(@book.id)
   else
     render :edit
   end
  end

  private
  def book_params
    params.require(:book).permit(:title, :image, :body)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end 
  
  def about
  end 
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
    @user = current_user
    @book = Book.new
  end

   def create
       @book = Book.new(book_params)
       @book.user_id = current_user.id
       @user = current_user
       @books = Book.all
    if @book.save
       flash[:notice] = 'You have created book successfully.'
       redirect_to books_path
    else
       render :index
    end

   end

  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books
  end

  def edit
     @user = User.find(params[:id])
  if @user != current_user
     redirect_to user_path(current_user.id)
  end
  end


   def update
          @user = User.find(params[:id])
      if  @user.update(user_params)
          redirect_to user_path(@user.id)
          flash[:notice] = 'You have updated user successfully.'
      else
          render :edit
      end

   end

    private
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_lisr.html.erb
        
        
        <% if @book.errors.any? %>
        <%= @book.errors.count %> errors prohibited this obj from being saved:
         <% @book.errors.full_messages.each do |message| %>
         <%= message %>
         <% end %>
         <% end %>

        <h1>User info</h1>
        <div>
         <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
        </div>

        <div>
          <table>
            <tr>
              <th>name</th>
              <td><%= @user.name %></td>
            </tr>
            <tr>
              <th>introduction</th>
              <td><%= @user.introduction %></td>
            </tr>
          </table>
        </div>

         <%= link_to "user edit", edit_user_path(@user.id) %>



        <h1>New book</h1>
       <%= form_with model: @book, local:true do |f| %>

         <h4>title</h4>
          <%= f.text_field :title %>
         <h4>opinion</h4>
          <%= f.text_area :opinion %>
         <%= f.submit 'create book' %>

        <% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

         <% if @book.errors.any? %>
         <%= @book.errors.count %> error prohibited this obj from being saved
         <% @book.errors.full_messages.each do |message| %>
         <%= message %>
         <% end %>
         <% end %>

<%= form_with model:@book, local:true do|f| %>
<p>Title
<%= f.text_field:title %></p>
<p>Opinion
<%= f.text_area:body %></p>

<%= f.submit 'Update Book' %>
<% end %>

<%= link_to "Show", book_path(@book.id) %>
|
<%= link_to "Back", books_path %>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">

      <div class="col-md-3">



        <% if @book.errors.any? %>
        <%= @book.errors.count %> errors prohibited this obj from being saved:
         <% @book.errors.full_messages.each do |message| %>
         <%= message %>
         <% end %>
         <% end %>


        <h1>User info</h1>
        <div>
         <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
        </div>

        <div>
          <table>
            <tr>
              <th>name</th>
              <td><%= @user.name %></td>
            </tr>
            <tr>
              <th>introduction</th>
              <td><%= @user.introduction %></td>
            </tr>
          </table>
        </div>
        
        

         <%= link_to "user edit", edit_user_path(@user.id), class:"fas fa-user-cog" %>


        <h1>New book</h1>
       <%= form_with model: @book, local:true do |f| %>

         <h4>title</h4>
          <%= f.text_field :title %>
         <h4>opinion</h4>
          <%= f.text_area :body %>
         <%= f.submit 'Create Book' %>

        <% end %>


      </div>


      <div class="col-md-8 offset-md-1">
    <tabel clss="table table-striped">

      <h1>Books</h1>

      <table>
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
          </tr>
        </thead>

        <% @books.each do |book|%>
        <tbody>
          <tr>
            <td><%= link_to user_path(book.user.id) do %>
                <%= attachment_image_tag book.user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
                <% end %></td>

            <td><%= link_to book_path(book.id) do %>
              <%= book.title %>
              <% end %></td>
            <td><%= book.body%></td>
          </tr>
        </tbody>
      <% end %>
      </table>

    </tabel>
      </div>

  </div>
</div>

app/views/books/show.html.erb
<div class="container">
  <div class="row">

      <div class="col-md-3">

         <% if @book.errors.any? %>
        <%= @book.errors.count %> errors prohibited this obj from being saved:
         <% @book.errors.full_messages.each do |message| %>
         <%= message %>
         <% end %>
         <% end %>

        <h1>User info</h1>
        <div>
         <%= attachment_image_tag @book.user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
        </div>

        <div>
          <table>
            <tr>
              <th>name</th>
              <td><%= @book.user.name %></td>
            </tr>
            <tr>
              <th>introduction</th>
              <td><%= @book.user.introduction %></td>
            </tr>
          </table>
        </div>

         <%= link_to "user edit", edit_user_path(@user.id), class:"fas fa-user-cog" %>


        <h1>New book</h1>
       <%= form_with model: @new_book, local:true do |f| %>

         <h4>title</h4>
          <%= f.text_field :title %>
         <h4>opinion</h4>
          <%= f.text_area :body %>
         <%= f.submit 'Create Book' %>

        <% end %>
      </div>

      <div class="col-md-8 offset-md-1">
    <tabel clss="table table-striped">

      <h1>Book detail</h1>
      <table>
        <tbody>
          <tr>
            <td> 
            <%= link_to user_path(@user.id) do %>
            <%= attachment_image_tag @book.user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
            <%= @user.name %>
            <% end %></td>

            <td><%= link_to @book.title, book_path(@book.id) %></td>

            <td><%= @book.body %></td>

            <td><% if @book.user == current_user %>
                 <%= link_to "Destroy", book_path(@book), method: :delete %>
                 <% end %>

            <td><% if @book.user == current_user %>
                <%= link_to "Edit", edit_book_path(@book) %>
                <% end %></td>
          </tr>
        </tbody>
      </table>

    </tabel>
      </div>

  </div>
</div>

app/views/homes/about.html.erb
<h1>Welcome to   <i class="fas fa-book" aria-hidden="true"></i>Bookers!</h1>

app/views/homes/top.html.erb
<h1 class="text-danger">welcome to Bookers  <i class="fas fa-book" aria-hidden="true"></i> !!</h1>
<p>In Bookers,</p>
<p>you can share and exchange your opinions , inpressions , and emotions<br>

about various books!</p>

<p><%= link_to "Log in", new_user_session_path, class: "btn btn-secondary" %></p>

<p><%= link_to "Sign up", new_user_registration_path,class: "btn btn-secondary2" %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
     <meta charset="UTF-8" />
     <script src="https://kit.fontawesome.com/3802808888.js" crossorigin="anonymous"></script>


    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
     <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <a class="navbar-brand p-3" href="/">Bookers</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">

     <% if user_signed_in? %>

      <li class="nav-item">
        <%= link_to "商品一覧", user_path(current_user.id), class:"fas fa-home" %>
      </li>

      <li class="nav-item">
         <%= link_to "会員一覧", users_path, class:"fas fa-users" %>
      </li>

      <li class="nav-item">
        <%= link_to "注文履歴一覧", books_path, class:"fas fa-book-open" %>
      </li>
      
      <li class="nav-item">
        <%= link_to "ジャンル一覧", books_path, class:"fas fa-book-open" %>
      </li>

      <li class="nav-item">
        <%= link_to "ログアウト", destroy_session_path, method: :delete, class:"fas fa-sign-out-alt" %>
      </li>
      
    <% else %>

      <li class="nav-item">
        <%= link_to "Home", root_path, class:"fas fa-home" %>
      </li>

      <li class="nav-item">
        <%= link_to "About", home_about_path, class:"fas fa-link" %>
      </li>

      <li class="nav-item">
        <%= link_to "Sign up", new_user_registration_path, class:"fas fa-user-plus" %>
      </li>

      <li class="nav-item">
        <%= link_to "Log in", new_user_session_path, class:"fas fa-sign-in-alt" %>
      </li>
    <% end %>
           </ul>
          </div>
        </div>
      </nav>
    </header>
    <main class="mb-auto">

　　<% flash.each do |key, value| %>
    <%= content_tag(:div, value, class: "#{key}") %>
 　 <% end %>

    <%= yield %>
    </main>

    <footer>
      CopyRight Infratop.inc
    </footer>


  </body>
</html>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">

      <div class="col-md-3">

        <% if @book.errors.any? %>
         <%= @book.errors.count %> errors prohibited this obj from being saved:
         <% @book.errors.full_messages.each do |message| %>
         <%= message %>
         <% end %>
         <% end %>

        <h1>User info</h1>
        <div>
          <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
        </div>

        <div>
          <table>
            <tr>
              <th>name</th>
              <td><%= @user.name %></td>
            </tr>
            <tr>
              <th>introduction</th>
              <td><%= @user.introduction %></td>
            </tr>
          </table>
        </div>

        <%= link_to "user edit", edit_user_path(@user.id),  class:"fas fa-user-cog" %>


        <h1>New book</h1>
       <%= form_with model: @book, local:true do |f| %>

         <h4>title</h4>
          <%= f.text_field :title %>
         <h4>opinion</h4>
          <%= f.text_area :body %>
         <%= f.submit 'Create Book' %>

        <% end %>

      </div>

      <div class="col-md-8 offset-md-1">
    <tabel clss="table table-striped">

      <h1>Users</h1>

      <table>
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th></th>
          </tr>
        </thead>

        <% @users.each do |user|%>
        <tbody>
          <tr>
            <td> <%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %></td>
            <td><%= user.name %></td>
            <td><%= link_to "Show", user_path(user.id) %></td>
          </tr>
        </tbody>
      <% end %>
      </table>

    </tabel>
      </div>

  </div>
</div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">

      <div class="col-md-3">

         <% if @book.errors.any? %>
        <%= @book.errors.count %> errors prohibited this obj from being saved:
         <% @book.errors.full_messages.each do |message| %>
         <%= message %>
         <% end %>
         <% end %>

        <h1>User info</h1>
        <div>
          <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
        </div>

        <div>
          <table>
            <tr>
              <th>name</th>
              <td><%= @user.name %></td>
            </tr>
            <tr>
              <th>introduction</th>
              <td><%= @user.introduction %></td>
            </tr>
          </table>
        </div>

         <%= link_to "user edit", edit_user_path(@user.id),  class:"fas fa-user-cog" %>


        <h1>New book</h1>
       <%= form_with model: @book, local:true do |f| %>

         <h4>title</h4>
          <%= f.text_field :title %>
         <h4>opinion</h4>
          <%= f.text_area :body %>
         <%= f.submit 'Create Book' %>

        <% end %>

      </div>

      <div class="col-md-8 offset-md-1">
    <tabel clss="table table-striped">

      <h1>Books</h1>

      <table>
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
          </tr>
        </thead>

        <% @books.each do |book|%>
        <tbody>
          <tr>
            <td><%= link_to user_path(book.user.id) do %>
                 <%= attachment_image_tag book.user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
                <% end %></td>

            <td><%= link_to book_path(book.id) do %>
              <%= book.title %>
              <% end %></td>
            <td><%= book.body %></td>
          </tr>
        </tbody>
      <% end %>
      </table>

    </tabel>
      </div>

  </div>
</div>